# Generated by Django 6.0.7 on 2026-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_preferred_currency_sellerwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='crypto_currency',
            field=models.CharField(choices=[('ETH', 'ETH'), ('SOL', 'SOL'), ('BTC', 'BTC'), ('USDT', 'USDT'), ('NGN', 'NGN')], default='ETH', max_length=10),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='state',
            field=models.CharField(blank=True, help_text='State / FCT', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerwallet',
            name='currency',
            field=models.CharField(choices=[('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('BTC', 'Bitcoin (BTC)'), ('USDT', 'Tether (USDT)'), ('NGN', 'Naira (NGN)'), ('BNB', 'BNB Smart Chain (BNB)'), ('MATIC', 'Polygon (MATIC)'), ('OTHER', 'Other Crypto')], default='ETH', max_length=20),
        ),
    ]
