# Generated by Django 6.0.7 on 2026-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_landlisting_crypto_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='crypto_currency',
            field=models.CharField(choices=[('ETH', 'ETH'), ('SOL', 'SOL'), ('BTC', 'BTC'), ('BNB', 'BNB')], default='ETH', max_length=10),
        ),
    ]
